apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vhp-core

resources:
  - namespace.yaml
  - priority-class.yaml
  - services/nginx-ingress.yaml
  - services/dns-gateway.yaml
  - services/mail-gateway.yaml
  - services/kyverno-deployment.yaml # Yeni polis motoru buraya eklendi