apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - policies/resourcequota.yaml
  - policies/limitrange.yaml
  - policies/networkpolicy.yaml

# Namespace ve RBAC .tpl olduğu için Controller tarafından 
# render edilip bu listeye eklenecek.