apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - [cite_start]deployment.yaml [cite: 6]
  - [cite_start]service.yaml [cite: 7]
  - [cite_start]pvc.yaml [cite: 7]
  - [cite_start]pdb.yaml [cite: 6]
  - [cite_start]../secret/placeholder.yaml [cite: 8]