apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-data
  namespace: cust-${CUSTOMER_ID}
  labels:
    tenant: "true"
    customer-id: "${CUSTOMER_ID}"
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
