apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - minio/kustomization.yaml
  - policies/resourcequota.yaml
  - policies/limitrange.yaml
  - policies/networkpolicy.yaml